export const rejectionReasons = {
  FACE_NOT_DETECTED: "FACE_NOT_DETECTED",
  FACE_NOT_RECOGNIZED: "FACE_NOT_RECOGNIZED",
  OUTSIDE_GEOFENCE: "OUTSIDE_GEOFENCE",
  OBJECT_NOT_ASSIGNED: "OBJECT_NOT_ASSIGNED",
  NOT_WORKING_DAY: "NOT_WORKING_DAY",
  ALREADY_INSIDE: "ALREADY_INSIDE",
  NOT_INSIDE: "NOT_INSIDE"
} as const;